### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Dayana-Turquetti** [moshi4/CafePlotter#1]
Hi, @moshi4! Thank you so much for your solution. 
I am trying to run cafeplotter, but I have this error: "too many values to unpack (expected 2).

Do I need to modify something in my result directory? Or that issue is about the content of my files? 

Thank you in advance, Dayana. 

Bellow, there is the complete command that I used: 

cafeplotter -i run_4/ -o run_4_cafe-plotter_results --format pdf

Parsing CAFE5 result files...

Traceback (most recent call last):
  File "/home/dayana/miniconda3/envs/mypython3/bin/cafeplotter", line 8, in <module>
    sys.exit(cafeplotter.main())
  File "/home/dayana/miniconda3/envs/mypython3/lib/python3.10/site-packages/cafeplotter/scripts/cafeplotter.py", line 18, in main
    run(**args.__dict__)
  File "/home/dayana/miniconda3/envs/mypython3/lib/python3.10/site-packages/cafeplotter/scripts/cafeplotter.py", line 39, in run
    cp = CafeParser(indir)
  File "/home/dayana/miniconda3/envs/mypython3/lib/python3.10/site-packages/cafeplotter/cafeparser.py", line 36, in __init__
    self.famid2asr_tree
  File "/home/dayana/miniconda3/envs/mypython3/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/dayana/miniconda3/envs/mypython3/lib/python3.10/site-packages/cafeplotter/cafeparser.py", line 101, in famid2asr_tree
    return {str(t.name): t for t in self.asr_trees}
  File "/home/dayana/miniconda3/envs/mypython3/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/dayana/miniconda3/envs/mypython3/lib/python3.10/site-packages/cafeplotter/cafeparser.py", line 130, in asr_trees
    return CafeTree(self.asr_tree_file).trees
  File "/home/dayana/miniconda3/envs/mypython3/lib/python3.10/site-packages/cafeplotter/cafeparser.py", line 273, in __init__
    taxonid, gene_count = node_name.split("_")
ValueError: too many values to unpack (expected 2)

**Comment by moshi4** [comment]
Hmm, I think the error is happening in the case where the organism name has `_`(underscore) in it.
I just created CafePlotter, so I didn't do enough pattern testing.

Sorry. I will fix it.

**Comment by moshi4** [comment]
Hi,

I released CafePlotter v0.1.1 with bug fixes.
I believe that the error presented here should now no longer occur.

Please install the latest (v0.1.1) version of CafePlotter with `pip install -U cafeplotter` and try again.

**Comment by Dayana-Turquetti** [comment]
Hi, @moshi4. Perfect! 
It is working now. 

Thank you very much.
